# Generated by Django 2.2 on 2019-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190612_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(default=9999, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('room_level', models.IntegerField(blank=True)),
                ('room_banner', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='cid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
