# Generated by Django 2.2 on 2019-06-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190614_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='room_id',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.Room'),
        ),
    ]
